version: '2.1'
services:
  procrastinate:
    build: .
    volumes:
      - "./procrastinate:/procrastinate_dev/procrastinate"
      - "./procrastinate_demo:/procrastinate_dev/procrastinate_demo"
    command: worker
    environment:
      PYTHONPATH: .
      PROCRASTINATE_APP: procrastinate_demo.app.app
      PGDATABASE: procrastinate
      PGHOST: postgres
      PGUSER: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    ports: ["5432:5432"]
    environment:
        POSTGRES_DB: procrastinate
